volumes:
  visit_count_db:

services:
  visit-count-generator:
    container_name: "visit-count-generator"
    hostname: "visit-count"
    image: visit-count-generator
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    environment:
      ASPNETCORE_URLS: "http://*:8000"
      ConnectionString: "Filename=/data/database.db;Connection=direct"
    volumes:
      - visit_count_db:/data/